version: '2'
services:
  nginx:
    image: nginx:1.12.1-alpine
    ports:
      - "80:80"
    volumes_from:
      - php
    volumes:
      - D:/html/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - D:/html/docker/nginx/php.conf:/etc/nginx/php.conf
    links:
      - "php:php"
  php:
    build: php
    volumes:
      - D:/html:/www
      - D:/html/docker/php/php5.6.31.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
      - "9001:9001"
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "gongyan"
      explicit_defaults_for_timestamp: 1
    volumes_from:
      - php
    ports:
      - "3306:3306" 
  redis:
    image: redis:3.2.10-alpine
    command: redis-server --appendonly yes
    volumes:
      - /html/docker/redis/data:/data
    ports:
      - "6379:6379"